-- Executar pelo DBA. Substitua RMS_PORTAL_CONNECTOR pelo usuário técnico criado
-- para o agente. Não conceder privilégios de escrita nem DBA.
GRANT SELECT ON RMS.AG1IENSA TO RMS_PORTAL_CONNECTOR;
GRANT SELECT ON RMS.AG1FENSA TO RMS_PORTAL_CONNECTOR;
GRANT SELECT ON RMS.AA3CITEM TO RMS_PORTAL_CONNECTOR;
GRANT SELECT ON RMS.AA1CTCON TO RMS_PORTAL_CONNECTOR;
GRANT SELECT ON RMS.AA1CFISC TO RMS_PORTAL_CONNECTOR;
GRANT SELECT ON RMS.AA2CTIPO TO RMS_PORTAL_CONNECTOR;
GRANT EXECUTE ON RMS.F_CRFCFOP TO RMS_PORTAL_CONNECTOR;
