#!/usr/bin/env python3
"""Copia o schema e os dados de db/portal.db para o PostgreSQL do portal.

Não aplica db/migrations/001–005 (candidato RLS / outro modelo).
Gera db/pg-column-case.json para o driver Node preservar camelCase.
"""
from __future__ import annotations

import json
import os
import sqlite3
import sys
import time
from pathlib import Path

ROOT = Path("/lider/portal-fornecedor")
SQLITE_PATH = ROOT / "db" / "portal.db"
CASE_PATH = ROOT / "db" / "pg-column-case.json"
ENV_PATH = ROOT / ".env.postgres"
SKIP_TABLES = {"sqlite_sequence"}
BATCH = 20_000


def load_env() -> dict[str, str]:
    env: dict[str, str] = {}
    if ENV_PATH.is_file():
        for line in ENV_PATH.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, v = line.split("=", 1)
            env[k] = v
    env.update({k: v for k, v in os.environ.items() if k.startswith("POSTGRES") or k == "DATABASE_URL"})
    return env


def sqlite_connect() -> sqlite3.Connection:
    con = sqlite3.connect(f"file:{SQLITE_PATH}?mode=ro", uri=True, timeout=120)
    con.row_factory = sqlite3.Row
    return con


def is_autoincrement(create_sql: str | None, pk_cols: list[str]) -> bool:
    if not create_sql or len(pk_cols) != 1:
        return False
    return "AUTOINCREMENT" in create_sql.upper()


def pg_col_type(decl: str, identity: bool) -> str:
    if identity:
        return "INTEGER GENERATED BY DEFAULT AS IDENTITY"
    t = (decl or "TEXT").upper()
    if t in {"INTEGER", "INT", "TINYINT", "SMALLINT", "MEDIUMINT", "BIGINT", "BOOLEAN", "BOOL"}:
        return "INTEGER"
    if t in {"REAL", "FLOAT", "DOUBLE", "DOUBLE PRECISION", "NUMERIC", "DECIMAL"}:
        return "DOUBLE PRECISION"
    return "TEXT"


def quote_ident(name: str) -> str:
    return '"' + name.replace('"', '""') + '"'


def create_table_sql(table: str, cols: list[sqlite3.Row], create_sql: str | None) -> str:
    pk_cols = [c["name"] for c in cols if c["pk"]]
    pk_cols = [c["name"] for c in sorted((c for c in cols if c["pk"]), key=lambda c: c["pk"])]
    identity = is_autoincrement(create_sql, pk_cols)
    pieces = []
    for c in cols:
        ident = identity and c["name"] in pk_cols and len(pk_cols) == 1
        typ = pg_col_type(c["type"], ident)
        line = f"  {c['name']} {typ}"
        if c["notnull"] and not ident:
            line += " NOT NULL"
        if c["dflt_value"] is not None and not ident:
            dflt = str(c["dflt_value"])
            if dflt.upper() == "CURRENT_TIMESTAMP":
                line += " DEFAULT CURRENT_TIMESTAMP"
            else:
                line += f" DEFAULT {dflt}"
        pieces.append(line)
    if pk_cols and not (identity and len(pk_cols) == 1):
        pieces.append(f"  PRIMARY KEY ({', '.join(pk_cols)})")
    elif identity and len(pk_cols) == 1:
        pieces.append(f"  PRIMARY KEY ({pk_cols[0]})")
    extra = ""
    if create_sql and "CHECK (id = 1)" in create_sql.replace("  ", " "):
        extra = ",\n  CONSTRAINT fillrate_politica_singleton CHECK (id = 1)"
        if extra.strip().startswith(","):
            pieces.append("  CONSTRAINT fillrate_politica_singleton CHECK (id = 1)")
    return f"CREATE TABLE IF NOT EXISTS {table} (\n" + ",\n".join(pieces) + "\n);"


def main() -> int:
    import argparse

    import psycopg

    parser = argparse.ArgumentParser(description="Copia portal.db → PostgreSQL")
    parser.add_argument(
        "--tables",
        default="",
        help="Lista separada por vírgula; vazio = todas. TRUNCATE+COPY se a tabela já existe.",
    )
    args = parser.parse_args()
    only = {t.strip() for t in args.tables.split(",") if t.strip()}

    env = load_env()
    dsn = env.get("DATABASE_URL")
    if not dsn:
        print("DATABASE_URL ausente (.env.postgres)", file=sys.stderr)
        return 2

    t0 = time.time()
    sqlite = sqlite_connect()
    tables = [
        r[0]
        for r in sqlite.execute(
            "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name"
        )
        if r[0] not in SKIP_TABLES
    ]
    case_map: dict[str, str] = {}
    print(f"sqlite {SQLITE_PATH} tables={len(tables)}", flush=True)

    with psycopg.connect(dsn, autocommit=False) as pg:
        pg.execute("SET client_min_messages TO WARNING")
        pg.execute("SET synchronous_commit TO OFF")
        cur = pg.cursor()
        existing = {r[0] for r in cur.execute("SELECT tablename FROM pg_tables WHERE schemaname='public'")}
        for table in tables:
            cols = list(sqlite.execute(f"PRAGMA table_info({table})"))
            create_sql = sqlite.execute(
                "SELECT sql FROM sqlite_master WHERE type='table' AND name=?", (table,)
            ).fetchone()[0]
            for c in cols:
                case_map[c["name"].lower()] = c["name"]
            if only and table in existing:
                print(f"  schema {table} keep (refresh)", flush=True)
                continue
            cur.execute(f"DROP TABLE IF EXISTS {table} CASCADE")
            ddl = create_table_sql(table, cols, create_sql)
            cur.execute(ddl)
            n = sqlite.execute(f'SELECT COUNT(*) FROM "{table}"').fetchone()[0]
            print(f"  schema {table} cols={len(cols)} rows={n}", flush=True)
        pg.commit()

        if only:
            tables = [t for t in tables if t in only]
            if not tables:
                print("nenhuma tabela pedida existe no sqlite", file=sys.stderr)
                return 2

        for table in tables:
            cols = [c["name"] for c in sqlite.execute(f"PRAGMA table_info({table})")]
            n = sqlite.execute(f'SELECT COUNT(*) FROM "{table}"').fetchone()[0]
            if only:
                cur.execute(f"TRUNCATE TABLE {table} RESTART IDENTITY CASCADE")
            if n == 0:
                pg.commit()
                print(f"  copy {table} skip empty", flush=True)
                continue
            col_list = ", ".join(cols)
            copy_sql = f"COPY {table} ({col_list}) FROM STDIN"
            sqlite_cur = sqlite.execute(f'SELECT {col_list} FROM "{table}"')
            copied = 0
            t1 = time.time()
            with cur.copy(copy_sql) as copy:
                while True:
                    rows = sqlite_cur.fetchmany(BATCH)
                    if not rows:
                        break
                    for row in rows:
                        copy.write_row(tuple(row))
                    copied += len(rows)
                    if copied % 200_000 == 0:
                        print(f"    {table} {copied}/{n}", flush=True)
            pg.commit()
            print(f"  copy {table} {copied} in {time.time()-t1:.1f}s", flush=True)

        for table in tables:
            cols = list(sqlite.execute(f"PRAGMA table_info({table})"))
            pk_cols = [c["name"] for c in sorted((c for c in cols if c["pk"]), key=lambda c: c["pk"])]
            create_sql = sqlite.execute(
                "SELECT sql FROM sqlite_master WHERE type='table' AND name=?", (table,)
            ).fetchone()[0]
            if is_autoincrement(create_sql, pk_cols):
                pk = pk_cols[0]
                cur.execute(
                    f"SELECT setval(pg_get_serial_sequence(%s, %s), COALESCE((SELECT MAX({pk}) FROM {table}), 1), true)",
                    (table, pk),
                )
        pg.commit()

        if not only:
            indexes = list(
                sqlite.execute(
                    "SELECT name, tbl_name, sql FROM sqlite_master WHERE type='index' AND sql IS NOT NULL ORDER BY name"
                )
            )
            for name, tbl, sql in indexes:
                ddl = sql.replace("IF NOT EXISTS", "").strip()
                if not ddl.upper().startswith("CREATE INDEX"):
                    continue
                try:
                    cur.execute(f"DROP INDEX IF EXISTS {name}")
                    cur.execute(ddl)
                except Exception as exc:
                    print(f"  index {name} FAIL {exc}", file=sys.stderr)
                    pg.rollback()
                    continue
            pg.commit()
        cur.execute("ANALYZE")
        pg.commit()

        print("verify", flush=True)
        mismatch = 0
        for table in tables:
            sq = sqlite.execute(f'SELECT COUNT(*) FROM "{table}"').fetchone()[0]
            pg_n = cur.execute(f"SELECT COUNT(*) FROM {table}").fetchone()[0]
            mark = "OK" if sq == pg_n else "DIFF"
            if sq != pg_n:
                mismatch += 1
            print(f"  {mark} {table:32} sqlite={sq} pg={pg_n}", flush=True)
        if mismatch:
            print(f"FAIL mismatches={mismatch}", file=sys.stderr)
            return 1

    CASE_PATH.write_text(json.dumps(case_map, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"case map {CASE_PATH} keys={len(case_map)} elapsed={time.time()-t0:.1f}s", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
